### ISSUE TITLE
Peer to peer code review: Tracy, Okumu, Allusin, Jonah.

### ISSUE THREAD

**Issue by TracyMuso** [Alusp/My-Portfolio#7]
-Kindly consider changing the background of the works container to be e5e5e5, that's how it is in the figma template.
-Please consider making the alt text of the social media icons more descriptive for accessibility's sake.
-Kindly increase the form field text-widths as they are too narrow.
-Please consider animating the images in the work section, especially on hover.

**Comment by Alusp** [comment]
Its done.
